name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Clojure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CLJ Lint
        id: lint
        uses: ./.github/actions/clj-lint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'Clojure Linting Report'